[Custom_Field]
Path = "Administration > Devices > Device Custom Fields"

Type = "Multi-line"


[Overview]
Custom_field_type = "Multi-line"
Label = "cPVAL Video Ports Monitors"
Name = "cpvalVideoPortsMonitors"
Custom_field_is_required = false

[Inheritance]
Device = true
End_User = false
Location = false
Organization = false

[Permissions]
Automation = "Read_Write"
API = "Read_Write"
Technician_access = "Editable"

[Details]
Description = "Detect all available video output ports on the system (HDMI, DisplayPort, VGA, DVI, etc.). Detect which ports are actively used by connected monitors."
Tooltip_text = ""
Footer_text = ""

[Device_Custom_Fields]

Path = "Administration > Devices > Roles"

[Device_Custom_Field.Role]
Role_Name = "windows desktop and laptop"
Custom_Field_Tab_Name = "Default fields"