[Custom_Field]
Path = "Administration > Organizations > Organization Custom Fields"

Type = "Text"

[Overview]
Custom_field_type = "Text"
Label = "cPVAL Todyl Desktop Policy Key"
Name = "cpvalTodylDesktopPolicyKey"
Custom_field_is_required = false

[Inheritance]
Device = false
End_User = false
Location = false
Organization = true

[Permissions]
Automation = "Read_Write"
API = "Read_Write"
Technician_access = "Editable"

[Details]
Description = "Todyl Deployment Key for Desktop Agents"
Tooltip_text = ""
Footer_text = ""

[Organization_Custom_Fields]
Path = "Administration > Organizations > Organization Custom Fields > Edit Custom Tab > Manage tabs"
Custom_Field_Tab_Name = "Todyl Deployment"