[Custom_Field]
Path = """Administration > Organizations > Organization Custom Fields / """

Type = """Text"""

[Overview]
Custom_field_type = "Text"
Label = "cPVAL Zorus Uninstallation Password"
Name = "cpvalZorusUninstallationPassword"
Custom_field_is_required = false

[Inheritance]
Device = true
End_User = false
Location = false
Organization = true

[Permissions]
Automation = "Read_Write"
API = "Read_Write""
Technician_access = "Editable"

[Details]
Description = "Zorus agent uninstallation password. To utilize this feature set this variable to your desired password. Only use this feature if you have a secure way to store/remember the desired password."
Tooltip_text = ""
Footer_text = ""