[Custom_Field]
Path = "Administration > Devices > Device Custom Fields"
Type = "Text"

[Overview]
Custom_field_type = "Text"
Label = "cPVAL ESU Status"
Name = "cpvalEsuStatus"
Custom_field_is_required = false

[Inheritance]
Device = true
End_User = false
Location = false
Organization = false

[Permissions]
Automation = "Read_Write"
API = "Read_Write"
Technician_access = "Read Only"

[Details]
Description = "This custom field stores the endpoint's ESU status"
Tooltip_text = "Windows 10 ESU Active License Status"
Footer_text = ""

[Device_Custom_Fields]

Path = "Administration > Devices > Roles"

[Device_Custom_Field.Role]
Role_Name = "Windows Desktops and Laptops/Windows Desktop"
Edit > Select an input field > Search cpval ESU Status > Add to the Default fields > Save
Custom_Field_Tab_Name = "Default fields"

[Organization_Custom_Field]

Path = "Administration > Organization custom fields"
Type = "Text"

[Overview]
Custom_field_type = "Text"
Label = "cPVAL ESU Key"
Name = "cpvalEsuKey"
Custom_field_is_required = false

[Inheritance]
Device = true
End_User = false
Location = true
Organization = true

[Permissions]
Automation = "Read_Write"
API = "Read_Write"
Technician_access = "Editable"

[Details]
Description = "Provide the ESU license key for activation of Windows 10 extended use."
Tooltip_text = ""
Footer_text = ""

[Organization_Custom_Field]

Path = "Administration > Organization custom fields"
Type = "Text"

[Overview]
Custom_field_type = "Text"
Label = "cPVAL ESU Year"
Name = "cpvalEsuYear"
Custom_field_is_required = false

[Inheritance]
Device = true
End_User = false
Location = true
Organization = true

[Permissions]
Automation = "Read_Write"
API = "Read_Write"
Technician_access = "Editable"

[Details]
Description = "Provide the license key year validation in numeric form, like 1, 2, or 3."
Tooltip_text = ""
Footer_text = ""