[Custom_Field]
Path = "Administration > Devices > Device Custom Fields"
Type = "Text"

[Overview]
Custom_field_type = "Text"
Label = "cPVAL SentinelOne Mgmt Server Url"
Name = "cpvalSentineloneMgmtServerUrl"
Custom_field_is_required = false

[Inheritance]
Device = true
End_User = false
Location = false
Organization = false

[Permissions]
Automation = "Read_Write"
API = "Read_Write"
Technician_access = "Editable"

[Details]
Description = "SentinelOne Management Server Url fetched from the Endpoint."
Tooltip_text = "SentinelOne Management Server Url fetched from the Endpoint."
Footer_text = "SentinelOne Mgmt Server Url"

[Device_Custom_Fields]

Path = "Administration > Devices > Roles"

[Device_Custom_Field.Role]
Role_Name = "Windows Desktops and Laptops"
Custom_Field_Tab_Name = "SentinelOne Management Server Url Wks"

[Device_Custom_Fields.Role]
Role_Name = "Windows Server"
Custom_Field_Tab_Name = "SentinelOne Management Server Url Svr"