[Custom_Field]
Path = "Administration > Devices > Device Custom Fields"
Type = "Text"

[Overview]
Custom_field_type = "Text"
Label = "cPVAL ESU Status"
Name = "cpvalEsuStatus"
Custom_field_is_required = false

[Inheritance]
Device = true
End_User = false
Location = false
Organization = false

[Permissions]
Automation = "Read_Write"
API = "Read_Write"
Technician_access = "Editable"

[Details]
Description = "This custom field stores the endpoint's ESU status."
Tooltip_text = "Windows 10 ESU Active License Status."
Footer_text = "Windows 10 ESU Active License Status."

[Device_Custom_Fields]

Path = "Administration > Devices > Roles"

[Device_Custom_Field.Role]
Role_Name = "Windows Desktops and Laptops"
Custom_Field_Tab_Name = "ESU Device"
Custom_Field_Tab_Description = "Custom Fields for Window 10 22H2 ESU License management."