[Group]
Path = "Administration > Device > Groups"

[Filters]

[Filters.More_filters]

[Filters.More_filters.Device]

[Filters.More_filters.Device.Custom_Fields]

[Filters.More_filters.Device.Custom_Fields.Has_all_conditions]
Custom_field = "cPVAL ESU Status"
Condition = "Contains"
Text = "ESU Activated"

[Save_device_group]
Name = "cPVAL Win10 ESU Activated"
Description = "This contains the list of Windows 10 devices where the ESU is activated."
Permission_type = "Self (Private) ━━ default"