[Compound_Condition]
Path = "Administration > Policies > Agent Policies"
Agent_Policy = "Windows Server"

[Conditions]
Trigger_when = "all conditions are true"

[Conditions.Script_result_condition]

[Conditions.Script_result_condition.Evaluation_script]
Evaluation_script = "SMB1 Access Audit and Detection"

[Conditions.Script_result_condition.Evaluation_script.Parameters]
Run_As = ""
Preset_Parameter = ""

[Conditions.Script_result_condition.Result_Code]
Operator = "equal to"
Result_Code = "1"

[Conditions.Script_result_condition.Timeout]
Hour = ""
Minutes = "10"

[Conditions.Script_result_condition.Output]
Operator = "Contains"
Text = "Microsoft-Windows-SMBServer"

Include_Script_Output_in_final_Alert = true

[Conditions.Script_result_condition.Script_error_notification]
Script_error_notification = false
Operator = ""
Result_Code = ""

[Conditions.Custom_Fields]

[Conditions.Custom_Fields.Custom_field_value_must_meet_ALL_conditions]
Custom_field = "cPVAL Roles Detected"
Condition = "Contains"
Text = "SMB1 Server"

[Settings]
Name = "SMB1 Traffic Audit"

[Settings.Auto_Reset]
After = false
Reset_Interval = ""
When_no_longer_met = true

Run_Every = "1 hour"

[Settings.Trigger_uptime]
Trigger_uptime = false
Minimum_uptime_for_trigger = ""

[Notifications]
Severity = "None"
Priority = "None"
Notify_Technicians = "Do not send notifications"
Notify_on_reset = false
Channels = ""
ConnectWise = "Create a ticket"

[Notifications.ConnectWise.Create_a_ticket]
Ticket_Template = "Default"
