[Compound_Condition]
Path = "Administration > Policies > Agent Policies"
Agent_Policy = "Windows Workstation"

[Conditions]
Trigger_when = "all conditions are true"

[Conditions.Custom_Fields]

[Conditions.Custom_Fields.Custom_field_value_must_meet_ANY_conditions]
Custom_field = "cPVAL Turn off Windows Firewall"
Condition = "equals"
Dropdown_value = "Windows Workstation and Windows Server"

[Conditions.Custom_Fields.Custom_field_value_must_meet_ANY_conditions]
Custom_field = "cPVAL Turn off Windows Firewall"
Condition = "equals"
Dropdown_value = "Windows Workstation"

[Conditions.Script_result_condition]

[Conditions.Script_result_condition.Evaluation_script]
Evaluation_script = "Get Windows Firewall Status"

[Conditions.Script_result_condition.Evaluation_script.Parameters]
Run_As = "System"

[Conditions.Script_result_condition.Result_Code]
Operator = "equal to"
Result_Code = "1"

[Conditions.Script_result_condition.Timeout]
Hour = "0"
Minutes = "5"

[Conditions.Script_result_condition.Output]
Operator = "Contains"
Text = "Firewall"

Include_Script_Output_in_final_Alert = false

[Conditions.Script_result_condition.Script_error_notification]
Script_error_notification = false

[Automations]

[Automations.Automation]
Name = "Disable Windows Firewall"

[Automations.Automation.Parameters]
Run_As = "System"
Preset_Parameter = ""

[Settings]
Name = "Turn off Windows Firewall"

[Settings.Auto_Reset]
After = true
Reset_Interval = "1 hour"
When_no_longer_met = true
Run_Every = "1 hour"

[Settings.Trigger_uptime]
Trigger_uptime = false

[Notifications]
Severity = "None"
Priority = "None"
Notify_Technicians = "Do not send notifications"
Notify_on_reset = false
Channels = ""
ConnectWise = "Do not create a ticket"
Ticketing_Rule = "Off"